### PR TITLE
Fix #59: Input#text => textarea

### LINKED ISSUE #59: Turn input field into text box

### PR DESCRIPTION
**Pull request by jimmcgaw**
This change converts the message input to a textarea for multiline
support. It also ups the font-size to 16px on the textarea so that
zooming on focus on mobile safari is disabled, which breaks the
responsive layout (and makes it easier to read). Add a button that
triggers the send operation. Persist the message on local state in the
form component, which we'll use when we add image attachment support.

### CODE REVIEW

**Comment by jimmcgaw** [comment]
👍

**Comment by elimisteve** [comment]
@jimmcgaw Thanks to your work plus https://github.com/cryptag/leapchat/pull/61/commits/d23904c5a4e85671e9828a4de51a837d49e72623 , sending a message works ideally on desktop as far as I'm concerned (where <enter> sends a message but `<shift>-<enter>` adds a newline).

On mobile, `<enter>` sends a message, which is probably fine(?), but `<shift>-<enter>` doesn't add a newline -- it just sends, which is kind of annoying. But pasting multi-line text works for me! But sending a message _by pressing the Send button_ removes focus from the textarea, thereby closing the keyboard, then opening it back up because of https://github.com/cryptag/leapchat/pull/61/commits/384984cc95535a487744a98dcd88777394a2a377 .

Thoughts?

**Comment by jimmcgaw** [comment]
Awesome! I was just now messing around with onChange and onKeyPress. You cracked it.

This works for me and it seems to work on Mobile iOS without any keyboard or focus issues. But you're saying there is a bug on Android?

**Comment by elimisteve** [comment]
> This works for me and it seems to work on Mobile iOS without any keyboard or focus issues. But you're saying there is a bug on Android?

Awesome. Well on Android, the keyboard disappears when you tap Send.

**Comment by elimisteve** [comment]
...and then https://github.com/cryptag/leapchat/pull/61/commits/384984cc95535a487744a98dcd88777394a2a377 gives the textarea focus again, so the keyboard sort of bounces closed then pops back open. _Bug_, pressing `<enter>` to send works great. And we couldn't send multi-line text on mobile (or anywhere else) before anyway, so... I could merge it?

**Comment by elimisteve** [comment]
@jimmcgaw :+1: Merged. And I'll deploy later today!

**Comment by elimisteve** [comment]
...[deployed!](https://www.leapchat.org/#CWC-AgreeingZodiacLicoriceLuxuriousCityscapeUraniumVicinityEpidemicQuoteDioxideItalicizeJukeboxEccentricBoroughRulebookPorcupineSinglesHurricaneDentistUnpavedEcosystemOperaOftentimesRebuiltPhrasing) :-D

**Pull request merged**
